version: '1'
services:
  backend:
    build: ./sectors
    container_name: sectors
    ports:
      - 8082:8082
  frontend:
    #build:
    #  context: .
    #  dockerfile: Dockerfile
    build: ./sectors-ui
    container_name: sectors-ui
    ports:
      - 4500:4500


