INSERT INTO sector VALUES (1, 'Manufacturing', null);
INSERT INTO sector VALUES (2, 'Construction materials', 1);
INSERT INTO sector VALUES (3, 'Electronics and Optics', 1);
INSERT INTO sector VALUES (4, 'Food and Beverage', 1);
INSERT INTO sector VALUES (5, 'Bakery confectionery products', 4);
INSERT INTO sector VALUES (6, 'Beverages', 4);
INSERT INTO sector VALUES (7, 'Fish fish products ', 4);
INSERT INTO sector VALUES (8, 'Meat meat products', 4);
INSERT INTO sector VALUES (9, 'Milk dairy products ', 4);
INSERT INTO sector VALUES (10, 'Other', 4);
INSERT INTO sector VALUES (11, 'Sweets snack food', 4);
INSERT INTO sector VALUES (12, 'Furniture', 1);
INSERT INTO sector VALUES (13, 'Bathroom/sauna ', 12);
INSERT INTO sector VALUES (14, 'Bedroom', 12);
INSERT INTO sector VALUES (15, 'Children’s room ', 12);
INSERT INTO sector VALUES (16, 'Kitchen ', 12);
INSERT INTO sector VALUES (17, 'Living room ', 12);
INSERT INTO sector VALUES (18, 'Office', 12);
INSERT INTO sector VALUES (19, 'Other (Furniture)', 12);
INSERT INTO sector VALUES (20, 'Outdoor ', 12);
INSERT INTO sector VALUES (21, 'Project furniture', 12);
INSERT INTO sector VALUES (22, 'Machinery', 1);
INSERT INTO sector VALUES (23, 'Machinery components', 22);
INSERT INTO sector VALUES (24, 'Machinery equipment/tools', 22);
INSERT INTO sector VALUES (25, 'Manufacture of machinery ', 22);
INSERT INTO sector VALUES (26, 'Maritime', 22);
INSERT INTO sector VALUES (27, 'Aluminium and steel workboats ', 26);
INSERT INTO sector VALUES (28, 'Boat/Yacht building', 26);
INSERT INTO sector VALUES (29, 'Ship repair and conversion', 26);
INSERT INTO sector VALUES (30, 'Metal structures', 22);
INSERT INTO sector VALUES (31, 'Other', 22);
INSERT INTO sector VALUES (32, 'Repair and maintenance service', 22);
INSERT INTO sector VALUES (33, 'Metalworking', 1);
INSERT INTO sector VALUES (34, 'Construction of metal structures', 33);
INSERT INTO sector VALUES (35, 'Houses and buildings', 33);
INSERT INTO sector VALUES (36, 'Metal products', 33);
INSERT INTO sector VALUES (37, 'Metal works', 33);
INSERT INTO sector VALUES (38, 'CNC-machining', 37);
INSERT INTO sector VALUES (39, 'Forgings, Fasteners ', 37);
INSERT INTO sector VALUES (40, 'Gas, Plasma, Laser cutting', 37);
INSERT INTO sector VALUES (41, 'MIG, TIG, Aluminum welding', 37);
INSERT INTO sector VALUES (42, 'Plastic and Rubber', 1);
INSERT INTO sector VALUES (43, 'Packaging', 42);
INSERT INTO sector VALUES (44, 'Plastic goods', 42);
INSERT INTO sector VALUES (45, 'Plastic processing technology', 42);
INSERT INTO sector VALUES (46, 'Blowing', 45);
INSERT INTO sector VALUES (47, 'Moulding', 45);
INSERT INTO sector VALUES (48, 'Plastics welding and processing', 45);
INSERT INTO sector VALUES (49, 'Plastic profiles', 42);
INSERT INTO sector VALUES (50, 'Printing ', 1);
INSERT INTO sector VALUES (51, 'Advertising', 50);
INSERT INTO sector VALUES (52, 'Book/Periodicals printing', 50);
INSERT INTO sector VALUES (53, 'Labelling and packaging printing', 50);
INSERT INTO sector VALUES (54, 'Textile and Clothing', 1);
INSERT INTO sector VALUES (55, 'Clothing', 54);
INSERT INTO sector VALUES (56, 'Textile', 54);
INSERT INTO sector VALUES (57, 'Wood', 1);
INSERT INTO sector VALUES (58, 'Other (Wood)', 57);
INSERT INTO sector VALUES (59, 'Wooden building materials', 57);
INSERT INTO sector VALUES (60, 'Wooden houses', 57);
INSERT INTO sector VALUES (61, 'Other', null);
INSERT INTO sector VALUES (62, 'Creative industries', 61);
INSERT INTO sector VALUES (63, 'Energy technology', 61);
INSERT INTO sector VALUES (64, 'Environment', 61);
INSERT INTO sector VALUES (65, 'Service', null);
INSERT INTO sector VALUES (66, 'Business services', 65);
INSERT INTO sector VALUES (67, 'Engineering', 65);
INSERT INTO sector VALUES (68, 'Information Technology and Telecommunications', 65);
INSERT INTO sector VALUES (69, 'Data processing, Web portals, E-marketing', 68);
INSERT INTO sector VALUES (70, 'Programming, Consultancy', 68);
INSERT INTO sector VALUES (71, 'Software, Hardware', 68);
INSERT INTO sector VALUES (72, 'Telecommunications', 68);
INSERT INTO sector VALUES (73, 'Tourism', 65);
INSERT INTO sector VALUES (74, 'Translation services', 65);
INSERT INTO sector VALUES (75, 'Transport and Logistics', 65);
INSERT INTO sector VALUES (76, 'Air', 75);
INSERT INTO sector VALUES (77, 'Rail', 75);
INSERT INTO sector VALUES (78, 'Road', 75);
INSERT INTO sector VALUES (79, 'Water', 75);
